openapi: '3.0.1'
info:
  title: Test allOf PHP
  version: '1.0'
paths:
  /test:
    get:
      tags: [ Test ]
      responses:
        default:
          description: Say hi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompoundDto'
components:
  schemas:
    CompoundDto:
      title: CompoundDto
      type: object
      properties:
        testProperty:
          description: Property using allOf
          allOf:
            - $ref: '#/components/schemas/TestDto'
    TestDto:
      title: TestDto
      type: object
      properties:
        name:
          type: string